PROBABILITY_OF_TREE = 1.0
INTERESTINGNESS=2 # the number of condition elements needed to reach an intentional bug
MAX_LAYERS_OF_TREE = 3
MIN_LAYERS_OF_TREE = 2
NUM_FUNCTIONS=2 # maximum number of functions to declare in the program
MAX_GLOBALS=2 # maximum number of global variables
MAX_NUMBER_OF_LEAFS_PER_LAYER=3
MIN_NUMBER_OF_LEAFS_PER_LAYER=1
MAX_NUMBER_OF_CONDITIONS_PER_LEAF = 1
MIN_NUMBER_OF_CONDITIONS_PER_LEAF = 1
MAX_NUMBER_OF_VARIABLES_PER_LEAF=2
MIN_NUMBER_OF_VARIABLES_PER_LEAF=1
MAX_NUMBER_OF_VARIABLES_PER_FXN=2
MIN_NUMBER_OF_VARIABLES_PER_FXN=1
MAX_NUMBER_OF_ELEMENTS_PER_LEAF = 5
MIN_NUMBER_OF_ELEMENTS_PER_LEAF = 0
MAX_NUMBER_OF_ELEMENTS_PER_FXN = 5
MIN_NUMBER_OF_ELEMENTS_PER_FXN = 0
PROBABILITY_OF_IF = 0.8 # a floating point number between 0.0 and 1.0 representing the probabilty of an Element being a PrimaryBranch or SecondaryBranch
MIN_NUM_BUGS=5 # the minimum number of bugs to be intentionally inserted
MAX_RECURSION=3 # the maximum number of recursive calls
PERCENT_BRANCH_VARIABLE=100 # the percent chance that a variable will spawn
MAX_BRANCH_VARIABLES=5 # the maximum number of variables spawned at the begining
PERCENT_BRANCH_EXPRESSION=100
MAX_BRANCH_EXPRESSIONS=5
MAX_FXN_VARIABLES=5
PERCENT_FXN_VARIABLES=100
MAX_FXN_EXPRESSIONS=10
PERCENT_FXN_EXPRESSIONS=100
MAX_NUM_OPERANDS=5 # the maximum number of operands in an operation
PRE_POST_CHANCE=10 # the percent chance that an operation right-hand operand will have a pre- or post-fixed increment or decrement
LEADING_ZEROS=3 # number of leading zeros in variable and function names
MAX_NUM_FXN_ARGS=3 # the maximum number of arguments for a random function
MAX_WORDS_RANDOM_STRING=10 # the number of words in a random string
MAX_LETTERS_RANDOM_STRING_WORD=10 # the maximum number of letters in a random string word
MAX_BUFF_LENGTH = 256 # the maximum number of elements in a buffer
